# Generated by Django 4.2.2 on 2023-08-21 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('discription', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(upload_to='media/Brand_image')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('parent', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(upload_to='media/Category_image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('customer_ID', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('start_date', models.DateField(max_length=50)),
                ('image', models.ImageField(upload_to='media/supplier_image')),
                ('Created_at', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('Updated_at', models.DateTimeField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_code', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('image', models.ImageField(default='ProductImg/noimg.jpg', upload_to='ProductImg')),
                ('hover_image', models.ImageField(blank=True, default='noimg.jpg', null=True, upload_to='ProductImg')),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('product_purchase_price', models.IntegerField()),
                ('sort_discription', models.TextField(blank=True, null=True)),
                ('discription', models.TextField()),
                ('aditional_discription', models.TextField(blank=True, null=True)),
                ('stock_quantity', models.PositiveIntegerField()),
                ('show_status', models.BooleanField(default=False)),
                ('flash_sale_add_and_expire_date', models.DateTimeField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_keyword', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos_dashboard.brand')),
                ('categoris', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_dashboard.category', verbose_name='Product Category')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('status', models.IntegerField()),
                ('payment_status', models.IntegerField()),
                ('total_quantity', models.IntegerField()),
                ('total', models.FloatField()),
                ('discount', models.FloatField(blank=True, null=True)),
                ('shipping_cost', models.FloatField(blank=True, null=True)),
                ('grand_total', models.FloatField()),
                ('paid', models.FloatField()),
                ('due', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('billing_date', models.DateField()),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('buy_price', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('whole_sale_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('total_descount', models.FloatField(blank=True, null=True)),
                ('sub_total', models.FloatField()),
                ('paid', models.FloatField()),
                ('due', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='media/')),
                ('Created_at', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('Updated_at', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='pos_dashboard.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='pos_dashboard.category')),
            ],
            options={
                'verbose_name': 'Purchase_Product',
                'verbose_name_plural': 'Purchase_Products',
            },
        ),
        migrations.CreateModel(
            name='return_purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'return_purchase',
                'verbose_name_plural': 'return_purchases',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('status', models.IntegerField()),
                ('payment_status', models.IntegerField()),
                ('total_quantity', models.IntegerField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('shipping_cost', models.FloatField(blank=True, null=True)),
                ('grand_total', models.FloatField()),
                ('paid', models.FloatField()),
                ('due', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos_dashboard.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('supplier_type', models.CharField(max_length=100)),
                ('supplier_ID', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('start_date', models.DateField(max_length=50)),
                ('amount', models.FloatField(max_length=30)),
                ('guarantor_name', models.CharField(max_length=100)),
                ('guarantor_phone', models.IntegerField()),
                ('Chassis_no', models.CharField(max_length=30)),
                ('Transport_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/supplier_image')),
                ('Created_at', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('Updated_at', models.DateTimeField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.CreateModel(
            name='Sales_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('billing_date', models.DateField()),
                ('product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('total_descount', models.FloatField(blank=True, null=True)),
                ('sub_total', models.FloatField()),
                ('paid', models.FloatField()),
                ('due', models.FloatField(blank=True, null=True)),
                ('Created_at', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('Updated_at', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos_dashboard.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos_dashboard.category')),
                ('customer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos_dashboard.customer')),
                ('sale_product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos_dashboard.purchase_product')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos_dashboard.unit')),
            ],
            options={
                'verbose_name': 'Sales_Product',
                'verbose_name_plural': 'Sales_Products',
            },
        ),
        migrations.CreateModel(
            name='Sale_order_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_dashboard.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_dashboard.sale')),
            ],
        ),
        migrations.AddField(
            model_name='purchase_product',
            name='supplier_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_Product', to='pos_dashboard.supplier'),
        ),
        migrations.AddField(
            model_name='purchase_product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='pos_dashboard.unit'),
        ),
        migrations.CreateModel(
            name='Purchase_order_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_dashboard.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_dashboard.purchase')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos_dashboard.supplier'),
        ),
    ]
